# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphOfRadialCity
                                 A QGIS plugin
 This plugin builds a graph of radial city for experimints for road networks.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-04-23
        copyright            : (C) 2023 by Rasin Oleg
        email                : RasinOV25@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GraphOfRadialCity class from file GraphOfRadialCity.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Build_Radial_Graph import GraphOfRadialCity
    return GraphOfRadialCity(iface)
