# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TAUNetCalcDialog
                                 A QGIS plugin
 Accessibility Calculations
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-29
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Evgeny Kleiman
        email                : evgenykleiman@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtCore import (Qt, pyqtSignal)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'tau_net_calc_settings_dialog_base.ui'))


class TAUNetSettingsCalcDialog(QtWidgets.QDialog, FORM_CLASS):
    dialogShown = pyqtSignal()
    def __init__(self, parent=None):
        """Constructor."""
        super(TAUNetSettingsCalcDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
    def showEvent(self, event):
        super(TAUNetSettingsCalcDialog, self).showEvent(event)
        self.dialogShown.emit()    
